// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB80EHlj24xSBxeu9lJBcREVDeCeVd5zR0',
    appId: '1:1023155540439:android:7613139974a4f7a3bffb92',
    messagingSenderId: '1023155540439',
    projectId: 'manalsoftech-6807e',
    storageBucket: 'manalsoftech-6807e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlNVGYhEaXbf8wnT-rjrNusGikYfB8MWs',
    appId: '1:1023155540439:ios:780771123f520a37bffb92',
    messagingSenderId: '1023155540439',
    projectId: 'manalsoftech-6807e',
    storageBucket: 'manalsoftech-6807e.appspot.com',
    androidClientId: '1023155540439-0e290i55k4278qrk00fpllp6ti6vvsfc.apps.googleusercontent.com',
    iosClientId: '1023155540439-velhd8sqtjbge40b5d9f0jpci0vqu304.apps.googleusercontent.com',
    iosBundleId: 'manal.mahakal.guruji',
  );

}